# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20171016_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 10, 16, 23, 8, 38, 186305, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
