# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20171016_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='slug',
        ),
    ]
